-- Run this migration in Supabase SQL Editor.
-- Auth users are created in Supabase Auth; passwords are never stored here.

create type public.app_role as enum ('user', 'admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  role public.app_role not null default 'user',
  competition_status text not null default 'active'
    check (competition_status in ('active', 'eliminated')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'username', ''),
    coalesce(new.raw_user_meta_data ->> 'display_name', new.email)
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role = 'admin'
  );
$$;

create table public.rounds (
  id bigint generated by default as identity primary key,
  round_number integer not null unique check (round_number > 0),
  name text not null,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'open', 'locked', 'complete', 'break')),
  first_kickoff timestamptz,
  created_at timestamptz not null default now()
);

create table public.teams (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true
);

create table public.fixtures (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.rounds(id) on delete restrict,
  kickoff timestamptz not null,
  location text not null default '',
  home_team_id bigint not null references public.teams(id) on delete restrict,
  away_team_id bigint not null references public.teams(id) on delete restrict,
  result text not null default 'pending'
    check (result in ('pending', 'home_win', 'away_win', 'draw', 'postponed', 'cancelled')),
  created_at timestamptz not null default now(),
  check (home_team_id <> away_team_id),
  unique (round_id, kickoff, home_team_id, away_team_id)
);

-- Safe to run against a database created from an earlier version.
alter table public.fixtures add column if not exists location text not null default '';

create table public.selections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  round_id bigint not null references public.rounds(id) on delete restrict,
  fixture_id bigint references public.fixtures(id) on delete restrict,
  team_id bigint not null references public.teams(id) on delete restrict,
  is_automatic boolean not null default false,
  selected_at timestamptz not null default now(),
  unique (user_id, round_id)
);

create index selections_user_id_idx on public.selections(user_id);
create index fixtures_round_id_idx on public.fixtures(round_id);

alter table public.profiles enable row level security;
alter table public.rounds enable row level security;
alter table public.teams enable row level security;
alter table public.fixtures enable row level security;
alter table public.selections enable row level security;

create policy "Users can read their profile"
  on public.profiles for select to authenticated
  using (id = (select auth.uid()) or public.is_admin());

-- Safe migration for profiles created before competition status was added.
alter table public.profiles add column if not exists competition_status text
  not null default 'active';

alter table public.profiles drop constraint if exists profiles_competition_status_check;
alter table public.profiles add constraint profiles_competition_status_check
  check (competition_status in ('active', 'eliminated'));

create policy "Authenticated users can read rounds"
  on public.rounds for select to authenticated using (true);

create policy "Authenticated users can read active teams"
  on public.teams for select to authenticated using (is_active or public.is_admin());

create policy "Authenticated users can read fixtures"
  on public.fixtures for select to authenticated using (true);

create policy "Users can read their own selections"
  on public.selections for select to authenticated
  using (user_id = (select auth.uid()) or public.is_admin());

create policy "Users can create their own selections"
  on public.selections for insert to authenticated
  with check (user_id = (select auth.uid()));

create policy "Admins can manage rounds"
  on public.rounds for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "Admins can manage teams"
  on public.teams for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "Admins can manage fixtures"
  on public.fixtures for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

create policy "Admins can manage profiles"
  on public.profiles for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- Exposes only leaderboard-safe fields. It does not expose roles or auth data.
create or replace view public.leaderboard_players as
select id, display_name, username, competition_status
from public.profiles;

revoke all on public.leaderboard_players from public;
revoke all on public.leaderboard_players from anon;
grant select on public.leaderboard_players to authenticated;

-- Storage bucket for admin-managed participant CSV imports.
insert into storage.buckets (id, name, public)
values ('participant-imports', 'participant-imports', false)
on conflict (id) do nothing;

create policy "Admins can manage participant imports"
  on storage.objects for all to authenticated
  using (bucket_id = 'participant-imports' and public.is_admin())
  with check (bucket_id = 'participant-imports' and public.is_admin());
