create table if not exists public.competition_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  entry_number integer not null check (entry_number > 0),
  name text not null,
  competition_status text not null default 'active'
    check (competition_status in ('active', 'eliminated')),
  eliminated_round_id bigint references public.rounds(id) on delete set null,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  unique (user_id, entry_number)
);

insert into public.competition_entries (
  user_id, entry_number, name, competition_status, eliminated_round_id
)
select profile.id,
  1,
  coalesce(nullif(profile.display_name, ''), profile.username, 'Entry') || ' - Entry 1',
  profile.competition_status,
  profile.eliminated_round_id
from public.profiles as profile
where not exists (
  select 1 from public.competition_entries as entry where entry.user_id = profile.id
);

alter table public.selections add column if not exists entry_id bigint;

update public.selections as selection
set entry_id = entry.id
from public.competition_entries as entry
where entry.user_id = selection.user_id
  and entry.entry_number = 1
  and selection.entry_id is null;

alter table public.selections alter column entry_id set not null;
alter table public.selections
  add constraint selections_entry_id_fkey
  foreign key (entry_id) references public.competition_entries(id) on delete cascade;

alter table public.selections
  drop constraint if exists selections_user_id_round_id_key;

create unique index if not exists selections_entry_id_round_id_key
  on public.selections(entry_id, round_id);

create index if not exists selections_entry_id_idx
  on public.selections(entry_id);

alter table public.round_processing_entries
  add column if not exists entry_id bigint references public.competition_entries(id) on delete set null;

update public.round_processing_entries as audit
set entry_id = selection.entry_id
from public.selections as selection
where audit.selection_id = selection.id
  and audit.entry_id is null;

alter table public.competition_entries enable row level security;

drop policy if exists "Users can read own competition entries"
  on public.competition_entries;
create policy "Users can read own competition entries"
  on public.competition_entries for select to authenticated
  using (user_id = (select auth.uid()) or public.is_admin());

drop policy if exists "Admins can manage competition entries"
  on public.competition_entries;
create policy "Admins can manage competition entries"
  on public.competition_entries for all to authenticated
  using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Authenticated users can read active teams" on public.teams;
create policy "Authenticated users can read teams"
  on public.teams for select to authenticated using (true);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_profile_id uuid;
begin
  insert into public.profiles (id, username, display_name)
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'username', ''),
    coalesce(new.raw_user_meta_data ->> 'display_name', new.email)
  )
  returning id into new_profile_id;

  insert into public.competition_entries(user_id, entry_number, name)
  values (new_profile_id, 1, coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), new.email) || ' - Entry 1');

  return new;
end;
$$;

create or replace function public.create_competition_entry()
returns public.competition_entries
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  next_entry_number integer;
  created_entry public.competition_entries;
  first_round_lockout timestamptz;
begin
  if auth.uid() is null then
    raise exception 'Sign-in is required to create an entry.';
  end if;

  perform pg_advisory_xact_lock(20260928, 1);

  perform 1 from public.profiles where id = auth.uid() for update;
  if not found then
    raise exception 'Player profile was not found.';
  end if;

  if exists (select 1 from public.round_processing_runs) then
    raise exception 'New entries are closed because competition processing has started.';
  end if;

  select coalesce(min(fixture.kickoff), min(round.first_kickoff)) - interval '2 hours'
  into first_round_lockout
  from public.rounds as round
  left join public.fixtures as fixture on fixture.round_id = round.id
  where round.status in ('open', 'scheduled');

  if first_round_lockout is not null and clock_timestamp() >= first_round_lockout then
    raise exception 'New entries are closed because the first-round selection deadline has passed.';
  end if;

  select coalesce(max(entry_number), 0) + 1
  into next_entry_number
  from public.competition_entries
  where user_id = auth.uid();

  insert into public.competition_entries(user_id, entry_number, name)
  values (
    auth.uid(),
    next_entry_number,
    coalesce((select nullif(display_name, '') from public.profiles where id = auth.uid()), 'Entry')
      || ' - Entry ' || next_entry_number
  )
  returning * into created_entry;

  return created_entry;
end;
$$;

revoke all on function public.create_competition_entry() from public, anon;
grant execute on function public.create_competition_entry() to authenticated;

create or replace function public.enforce_selection_deadline()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  round_status text;
  configured_kickoff timestamptz;
  first_kickoff timestamptz;
  entry_owner uuid;
  entry_status text;
begin
  if tg_op = 'DELETE' then
    return old;
  end if;

  if auth.uid() is not null then
    if new.user_id <> auth.uid() then
      raise exception 'You can only change your own selection.';
    end if;
    if tg_op = 'UPDATE'
      and (new.user_id <> old.user_id or new.round_id <> old.round_id or new.entry_id <> old.entry_id) then
      raise exception 'A saved selection cannot be moved to another user, round, or entry.';
    end if;
    new.is_automatic := false;
    new.selection_source := 'MANUAL';
  elsif new.selection_source = 'AUTO' and new.is_automatic then
    return new;
  end if;

  select user_id, competition_status
  into entry_owner, entry_status
  from public.competition_entries
  where id = new.entry_id
  for update;

  if not found or entry_owner <> new.user_id then
    raise exception 'The selected entry does not belong to this account.';
  end if;
  if entry_status <> 'active' then
    raise exception 'This entry has been eliminated and cannot make or change selections.';
  end if;

  select status, rounds.first_kickoff
  into round_status, configured_kickoff
  from public.rounds
  where id = new.round_id
  for update;
  if not found then
    raise exception 'The selected round does not exist.';
  end if;

  select coalesce(min(kickoff), configured_kickoff)
  into first_kickoff
  from public.fixtures
  where round_id = new.round_id;

  if first_kickoff is null then
    raise exception 'This round has no kickoff time, so selections are unavailable.';
  end if;
  if round_status not in ('open', 'scheduled')
    or clock_timestamp() >= first_kickoff - interval '2 hours' then
    raise exception 'Selections are now locked for this round.';
  end if;

  if new.fixture_id is not null and not exists (
    select 1 from public.fixtures
    where id = new.fixture_id
      and round_id = new.round_id
      and new.team_id in (home_team_id, away_team_id)
  ) then
    raise exception 'The selected team is not in that round fixture.';
  end if;

  if exists (
    select 1 from public.selections
    where entry_id = new.entry_id
      and team_id = new.team_id
      and round_id <> new.round_id
  ) then
    raise exception 'This entry has already selected this team in another round.';
  end if;

  return new;
end;
$$;

create or replace view public.leaderboard_entries as
select entry.id,
  entry.user_id,
  entry.name as entry_name,
  coalesce(profile.display_name, profile.username, 'Unnamed player') as display_name,
  profile.username,
  entry.competition_status,
  entry.eliminated_round_id
from public.competition_entries as entry
join public.profiles as profile on profile.id = entry.user_id;

revoke all on public.leaderboard_entries from public, anon;
grant select on public.leaderboard_entries to authenticated;

create or replace function public.allocate_overdue_round_selections()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  round_record record;
  entry_record record;
  team_id_to_assign bigint;
  fixture_id_for_team bigint;
  assigned_count integer := 0;
  first_kickoff timestamptz;
begin
  for round_record in
    select id, status, first_kickoff
    from public.rounds
    where status in ('open', 'scheduled')
    order by id
    for update skip locked
  loop
    select coalesce(min(kickoff), round_record.first_kickoff)
    into first_kickoff
    from public.fixtures
    where round_id = round_record.id;
    if first_kickoff is null or clock_timestamp() < first_kickoff - interval '2 hours' then
      continue;
    end if;

    for entry_record in
      select id, user_id
      from public.competition_entries
      where competition_status = 'active'
        and not exists (
          select 1 from public.selections
          where entry_id = competition_entries.id and round_id = round_record.id
        )
      order by id
    loop
      select team.id, fixture.id
      into team_id_to_assign, fixture_id_for_team
      from public.teams as team
      join public.fixtures as fixture
        on fixture.round_id = round_record.id
       and team.id in (fixture.home_team_id, fixture.away_team_id)
      where team.is_active
        and not exists (
          select 1 from public.selections
          where entry_id = entry_record.id and team_id = team.id
        )
      order by team.name, team.id, fixture.kickoff
      limit 1;

      if team_id_to_assign is null then continue; end if;

      insert into public.selections (
        user_id, entry_id, round_id, fixture_id, team_id, is_automatic, selection_source
      ) values (
        entry_record.user_id, entry_record.id, round_record.id,
        fixture_id_for_team, team_id_to_assign, true, 'AUTO'
      ) on conflict (entry_id, round_id) do nothing;

      if found then assigned_count := assigned_count + 1; end if;
      team_id_to_assign := null;
      fixture_id_for_team := null;
    end loop;

    update public.rounds set status = 'locked'
    where id = round_record.id and status in ('open', 'scheduled');
  end loop;
  return assigned_count;
end;
$$;

create or replace function public.process_round(
  p_round_id bigint,
  p_confirm_reprocess boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  round_record record;
  entry_record record;
  selection_record record;
  run_id bigint;
  run_number integer;
  fixture_count integer;
  v_active_count integer;
  v_eliminated_count integer := 0;
  outcome_value text;
  result_value text;
  status_before_value text;
  status_after_value text;
  expected_result text;
begin
  if not public.is_admin() then raise exception 'Admin access required.'; end if;

  perform pg_advisory_xact_lock(20260928, 1);

  select id, round_number, status, draw_rule into round_record
  from public.rounds where id = p_round_id for update;
  if not found then raise exception 'The selected round does not exist.'; end if;

  if exists (select 1 from public.round_processing_runs where round_id = p_round_id)
    and not p_confirm_reprocess then
    raise exception 'This round has already been processed. Confirm reprocessing to continue.';
  end if;
  if exists (
    select 1 from public.round_processing_runs as processing
    join public.rounds as processed_round on processed_round.id = processing.round_id
    where processed_round.round_number > round_record.round_number
  ) then
    raise exception 'This round cannot be reprocessed after a later round has been processed.';
  end if;

  select count(*) into fixture_count from public.fixtures where round_id = p_round_id;
  if fixture_count = 0 then raise exception 'This round has no fixtures.'; end if;
  if exists (
    select 1 from public.fixtures where round_id = p_round_id
      and ((home_score is null or away_score is null)
        and result not in ('home_win', 'away_win', 'draw'))
  ) then
    raise exception 'Every fixture needs a saved score or recorded result before processing.';
  end if;

  if exists (
    select 1 from public.competition_entries as entry
    where (entry.competition_status = 'active' or entry.eliminated_round_id = p_round_id)
      and not exists (
        select 1 from public.selections as selection
        join public.fixtures as fixture on fixture.id = selection.fixture_id
          and fixture.round_id = selection.round_id
          and selection.team_id in (fixture.home_team_id, fixture.away_team_id)
        where selection.entry_id = entry.id and selection.round_id = p_round_id
      )
  ) then
    raise exception 'Every active entry must have a valid selection for this round.';
  end if;

  select coalesce(max(processing.run_number), 0) + 1 into run_number
  from public.round_processing_runs as processing where processing.round_id = p_round_id;
  insert into public.round_processing_runs(round_id, run_number, processed_by)
  values (p_round_id, run_number, auth.uid()) returning id into run_id;

  for entry_record in
    select entry.id, entry.user_id, entry.name,
      entry.competition_status, entry.eliminated_round_id
    from public.competition_entries as entry
    where entry.competition_status = 'active' or entry.eliminated_round_id = p_round_id
    order by entry.id
  loop
    select selection.id as selection_id, selection.team_id, team.name as team_name,
      fixture.id as fixture_id, fixture.home_team_id, fixture.away_team_id,
      home_team.name || ' vs ' || away_team.name as fixture_label,
      fixture.home_score, fixture.away_score, fixture.result
    into selection_record
    from public.selections as selection
    join public.fixtures as fixture on fixture.id = selection.fixture_id
      and fixture.round_id = selection.round_id
      and selection.team_id in (fixture.home_team_id, fixture.away_team_id)
    join public.teams as team on team.id = selection.team_id
    join public.teams as home_team on home_team.id = fixture.home_team_id
    join public.teams as away_team on away_team.id = fixture.away_team_id
    where selection.entry_id = entry_record.id and selection.round_id = p_round_id;

    if selection_record.home_score is not null then
      result_value := case
        when selection_record.home_score > selection_record.away_score then 'home_win'
        when selection_record.home_score < selection_record.away_score then 'away_win'
        else 'draw'
      end;
    else
      result_value := selection_record.result;
    end if;

    expected_result := case
      when result_value = 'draw' then round_record.draw_rule
      when result_value = 'home_win' and selection_record.team_id = selection_record.home_team_id then 'survive'
      when result_value = 'away_win' and selection_record.team_id = selection_record.away_team_id then 'survive'
      else 'eliminate'
    end;
    outcome_value := case when expected_result = 'survive' then 'survived' else 'eliminated' end;
    status_before_value := entry_record.competition_status;
    status_after_value := case when outcome_value = 'survived' then 'active' else 'eliminated' end;

    update public.competition_entries
    set competition_status = status_after_value,
      eliminated_round_id = case when status_after_value = 'eliminated' then p_round_id else null end,
      updated_at = clock_timestamp()
    where id = entry_record.id;

    if status_before_value <> 'eliminated' and status_after_value = 'eliminated' then
      v_eliminated_count := v_eliminated_count + 1;
    end if;

    insert into public.round_processing_entries (
      run_id, entry_id, profile_id, participant_name, selection_id,
      selected_team_id, selected_team_name, fixture_id, fixture_label,
      fixture_result, home_score, away_score, outcome, status_before, status_after
    ) values (
      run_id, entry_record.id, entry_record.user_id, entry_record.name,
      selection_record.selection_id, selection_record.team_id, selection_record.team_name,
      selection_record.fixture_id, selection_record.fixture_label, result_value,
      selection_record.home_score, selection_record.away_score, outcome_value,
      status_before_value, status_after_value
    );
  end loop;

  update public.profiles as profile
  set competition_status = case
        when exists (
          select 1 from public.competition_entries as entry
          where entry.user_id = profile.id and entry.competition_status = 'active'
        ) then 'active'
        else 'eliminated'
      end,
      eliminated_round_id = case
        when exists (
          select 1 from public.competition_entries as entry
          where entry.user_id = profile.id and entry.competition_status = 'active'
        ) then null
        else (
          select max(entry.eliminated_round_id)
          from public.competition_entries as entry where entry.user_id = profile.id
        )
      end,
      updated_at = clock_timestamp()
  where exists (
    select 1 from public.competition_entries as entry where entry.user_id = profile.id
  );

  select count(*) into v_active_count from public.competition_entries
  where competition_status = 'active';
  update public.rounds set status = 'complete', processed_at = clock_timestamp()
  where id = p_round_id;
  update public.round_processing_runs set active_count = v_active_count,
    eliminated_count = v_eliminated_count where id = run_id;

  return jsonb_build_object('run_id', run_id, 'run_number', run_number,
    'round_number', round_record.round_number, 'active_count', v_active_count,
    'eliminated_count', v_eliminated_count);
end;
$$;

revoke all on function public.allocate_overdue_round_selections() from public, anon, authenticated;
revoke all on function public.process_round(bigint, boolean) from public, anon;
grant execute on function public.process_round(bigint, boolean) to authenticated;
